name: wgwwebapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.1
  go_router: ^16.1.0
  animated_text_kit: ^4.2.2
  
  mailer: ^6.0.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  video_player: ^2.9.2
  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.5.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  http_parser: ^4.0.0
  lottie: ^3.3.1
  animate_do: ^4.2.0
  mime: ^2.0.0
  
  font_awesome_flutter: ^10.8.0
  flutter_staggered_animations: ^1.1.1

  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  url_launcher: ^6.1.11
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
google_fonts: ^6.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/images/wgwlogo.png
    - assets/images/images/design1.png
    - assets/images/wgw.jpg
    - assets/images/build1.jpg
    - assets/images/build2.jpg
    - assets/images/build3.jpg
    - assets/images/build5.jpg
    - assets/images/Cont1.jpg
    - assets/images/build.jpg
    - assets/images/civil.jpg
    - assets/images/res.jpg
    - assets/images/mep.jpg
    - assets/images/road.png
    - assets/images/renovate.jpg
    - assets/images/interior.jpg
    - assets/images/manpower.jpg
    - assets/images/event.jpg
    - assets/images/manpower1.jpg
    - assets/images/manpower2.jpg
    - assets/images/manpower3.jpg
    - assets/icon/favicon.ico
    - assets/animations/workforce.json
    - assets/images/housekeeping.jpg
    - assets/images/saudi.jpg
    - assets/images/jeddah.webp
    - assets/images/uae.jpg
    - assets/images/MEP_Services.jpg
    - assets/images/local.jpg
    - assets/images/global.jpg
    - assets/images/executive.jpg
    - assets/images/virtual.jpg
    - assets/images/exe.jpg
    - assets/images/wgw.png
    - assets/images/job.jpg
    - assets/images/Muscat.jpg
    - assets/icon/construction.png
    - assets/icon/tech.png
    - assets/icon/health.png
    - assets/icon/hosp.png
    - assets/icon/power.jpg
    - assets/icon/manufacturing.png
    - assets/images/futureofmepdesing.jpg
    - assets/images/industry/cons.png
    - assets/images/industry/bpo.jpg
    - assets/images/industry/oil.jpg
    - assets/images/industry/health.jpg
    - assets/images/industry/hosp.jpg
    - assets/images/industry/power.jpg
    - assets/images/industry/manu.jpg
    - assets/images/industry/tele.jpg
    - assets/images/industry/bpo.jpg
    - assets/images/industry/ban2.jpg
    - assets/images/industry/aviation.jpg
    - assets/images/industry/tech.jpg
    - assets/images/industry/finance.jpg
    - assets/images/industry/finance.jpg
    - assets/images/construction/construction4.jpg
    - assets/images/servicescons/general.jpg
    - assets/images/servicescons/design.jpg
    - assets/images/servicescons/civil.jpg
    - assets/images/servicescons/res.jpg
    - assets/images/servicescons/renovation.jpg
    - assets/images/servicescons/mep.jpg
    - assets/images/servicescons/interior.jpg

    - assets/images/images/logistics.jpg
    - assets/images/images/log1.jpg
    - assets/images/images/log2.jpg
    - assets/images/images/log3.jpg
    - assets/images/images/log4.jpg
    - assets/images/images/log5.jpg
    - assets/images/images/newlog.webp
    - assets/images/images/newlog2.webp
    - assets/images/images/newlog3.webp
    - assets/images/images/freight.jpg
    - assets/images/images/supplychain.jpg
    - assets/images/images/inventory.jpg
    - assets/images/images/distribution.jpg
    - assets/images/images/consult.jpg
    - assets/images/images/ecomerce.jpg
    - assets/images/images/warehouse.jpg
    - assets/images/images/warehouse2.jpg
    - assets/images/images/custom.jpg
    - assets/images/images/pexels1.webp
    - assets/images/images/pexels2.jpeg
    - assets/images/images/pexels3.jpeg
    - assets/images/images/pexels4.jpeg
    - assets/images/images/port.jpg
    - assets/images/images/port4.jpg
    - assets/images/images/road.jpg
    - assets/images/images/ship.jpg
    - assets/images/images/MWT.png
    - assets/images/images/hamburg.jpg
    - assets/images/images/newhero1.jpg
    - assets/images/images/hero4.jpg
    - assets/images/images/project2.jpg
    - assets/images/images/dg.jpeg
    - assets/images/images/pack.jpeg
    - assets/images/images/custom.jpeg
    - assets/images/images/warehouseservice.jpeg
    - assets/images/images/land.jpeg
    - assets/images/images/air.webp
    - assets/images/images/ocean.jpeg
    - assets/images/images/airservice.png
    - assets/images/images/landservice.jpg
    - assets/images/images/landservice2.jpg
    - assets/images/images/ocean2.jpg
    - assets/images/images/MWT1.png
    - assets/images/Event/EM.jpg
    - assets/icon/favicon.ico
    - assets/images/b1.jpg
    - assets/images/b2.jpg
    - assets/images/b3.jpeg
    - assets/images/b4.webp
    - assets/images/b5.jpeg
    - assets/images/b6.webp



  fonts:
      - family: FiraSans
        fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
        - asset: assets/fonts/FiraSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/FiraSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraSans-Light.ttf
          weight: 300
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/Roboto-Regular.ttf
    #     - asset: assets/fonts/Roboto-Bold.ttf
    #     - asset: assets/fonts/Roboto-Light.ttf
    #     - asset: assets/fonts/Roboto-Medium.ttf
    #       weight: 700
